import 'package:flutter/material.dart';

import '../settings/settings_repository.dart';

class WmnLocaleController extends ChangeNotifier {
  WmnLocaleController(this.settings)
      : _languageCode = settings.getString('language', fallback: 'ar');

  final SettingsRepository settings;
  String _languageCode;

  String get languageCode => _languageCode;
  Locale get locale => Locale(_languageCode);
  bool get isRtl => _languageCode == 'ar';

  void setLanguage(String languageCode) {
    if (languageCode == _languageCode) return;
    _languageCode = languageCode;
    settings.setString('language', languageCode);
    notifyListeners();
  }
}

class WmnStrings {
  const WmnStrings(this.languageCode);

  final String languageCode;

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'frappe_runtime': 'Frappe-Compatible Runtime',
      'frappe_runtime_native_help': 'WMN implements Frappe framework contracts natively. Frappe source is a reference specification, not an executable runtime dependency.',
      'frappe_api_compatibility': 'Frappe API Compatibility',
      'api_weighted_coverage': 'Weighted API coverage',
      'runtime_engines': 'Runtime Engines',
      'source_api': 'Source API',
      'target_api': 'WMN Equivalent',
      'current_user': 'Current User',
      'roles': 'Roles',
      'queued_jobs': 'Queued Jobs',
      'failed_jobs': 'Failed Jobs',
      'desk': 'Desk / Framework',
      'application_platform': 'Application Platform',
      'home': 'Home',
      'current_ui': 'Current UI',
      'workspace_ui': 'Workspace UI',
      'workspace_home_title': 'My Workspaces',
      'workspace_home_description': 'Open only the workspace you need. System, administration, developer and application tools stay organized inside their workspaces.',
      'workspace_system': 'System',
      'workspace_administration': 'Administration',
      'workspace_developer': 'Developer',
      'quick_start': 'Quick Start',
      'platform_home_headline': 'Build any application on one clean WMN foundation',
      'platform_home_description': 'WMN provides reusable system capabilities, metadata-driven documents, workspaces and platform adapters so future applications can be delivered without rebuilding the foundation.',
      'platform_home_doctypes_help': 'Design reusable DocTypes, fields and document behavior.',
      'platform_home_methods_help': 'Manage global server Method modules, scripts, validation and revisions.',
      'platform_home_modules_help': 'Review and enable the system capabilities available to applications.',
      'platform_no_workspaces_help': 'No application workspaces are installed yet. Future applications can register their own workspaces without changing WMN Core.',
      'system_modules': 'System Modules',
      'system_modules_help': 'WMN system capabilities are independent from business applications. Required foundation modules stay enabled; optional capabilities can be enabled only when an application needs them.',
      'system_services': 'System Services',
      'platform_adapters': 'Platform Adapters',
      'current_platform': 'Current Platform',
      'active_adapters': 'Active Adapters',
      'platform_capabilities': 'Platform Capabilities',
      'platform_services': 'Platform Services',
      'system_module': 'System Module',
      'system_services_help': 'Inspect WMN files, jobs, notifications, logs, audit history, configuration and runtime health from one platform-neutral center.',
      'overview': 'Overview',
      'files': 'Files',
      'jobs': 'Jobs',
      'logs': 'Logs',
      'notifications': 'Notifications',
      'audit': 'Audit',
      'unread_notifications': 'Unread notifications',
      'error_logs': 'Error logs',
      'pending_print_jobs': 'Pending print jobs',
      'configuration_entries': 'Configuration entries',
      'audit_entries': 'Audit entries',
      'runtime_health': 'Runtime Health',
      'kernel_state': 'Kernel state',
      'storage_kind': 'Storage kind',
      'capture_diagnostics': 'Capture diagnostics',
      'scheduler_jobs': 'Scheduler & Background Jobs',
      'enqueue_due_schedules': 'Enqueue due schedules',
      'run_next_job': 'Run next job',
      'schedules': 'Schedules',
      'no_jobs': 'No system jobs have been queued yet.',
      'no_files': 'No platform files or attachments are stored yet.',
      'no_notifications': 'No notifications are available.',
      'mark_read': 'Mark as read',
      'no_logs': 'No system log entries are available.',
      'no_audit_entries': 'No audit entries are available.',
      'configuration': 'Configuration',
      'add_setting': 'Add setting',
      'scope': 'Scope',
      'scope_key': 'Scope key',
      'setting_key': 'Setting key',
      'setting_value': 'Setting value',
      'secret': 'Secret value',
      'add_file': 'Add file',
      'file_content_mode': 'File content mode',
      'managed_storage': 'Managed Storage',
      'managed_storage_help': 'Copy the file into WMN Storage and manage its lifecycle inside the platform.',
      'external_reference': 'External Reference',
      'external_reference_help': 'Keep the original file in place and store only its reference. Availability depends on the platform adapter.',
      'external_reference_unavailable': 'External file references are not available on this platform.',
      'export_file': 'Export file',
      'file_export_unsupported': 'File export is not available on this platform.',
      'attachments': 'Attachments',
      'add_attachment': 'Add attachment',
      'no_attachments': 'No attachments are linked to this record.',
      'detach_attachment': 'Detach attachment',
      'no_configuration_entries': 'No scoped configuration entries are defined yet.',
      'enabled_modules': 'Enabled modules',
      'ready_modules': 'Ready modules',
      'build': 'Build',
      'developer_tools': 'Developer Tools',
      'developer_center': 'Developer Center',
      'developer_center_help': 'Inspect the WMN kernel, service registry, capabilities, module dependencies, application manifests and native extension points from one place.',
      'capability_registry': 'Capability Registry',
      'capability_profiles': 'Capability Profiles',
      'system_module_dependencies': 'System Module Dependencies',
      'system_doctype_runtime_ownership': 'System DocType Runtime Ownership',
      'runtime_owner': 'Runtime Owner',
      'runtime_kind': 'Runtime Kind',
      'generic_editing_allowed': 'Generic editing allowed',
      'application_manifests': 'Application Manifests',
      'extension_points': 'Extension Points',
      'registered_services': 'Registered services',
      'available_capabilities': 'Available capabilities',
      'provided_by': 'Provided by',
      'no_dependencies': 'No system dependencies',
      'system_depends_on': 'Depends on',
      'kernel_healthy': 'Kernel healthy',
      'kernel_degraded': 'Kernel needs attention',
      'capability_available': 'Available',
      'capability_disabled': 'Disabled',
      'capability_unavailable': 'Unavailable',
      'module_has_enabled_dependents': 'This module is still required by another enabled system module.',
      'app_converter': 'App Converter',
      'compatibility_runtime': 'Compatibility Runtime',
      'platform_settings': 'Platform Settings',
      'feature_management': 'Features & Plans',
      'feature_management_help': 'Optional features run only when your plan/license grants them and you choose to enable them. Core platform features cannot be disabled.',
      'feature_core_included': 'Core • Included',
      'feature_not_entitled': 'Not included in current entitlement',
      'global_search': 'Search workspaces, app routes, DocTypes and modules',
      'no_search_results': 'No matching workspace, application route, DocType or system module was found.',
      'expand_sidebar': 'Expand sidebar',
      'collapse_sidebar': 'Collapse sidebar',
      'shell_layout': 'Shell Layout',
      'compact_navigation': 'Compact navigation',
      'compact_navigation_help': 'Reduce navigation row height while keeping the same capabilities.',
      'show_workspace_labels': 'Show workspace labels',
      'light': 'Light',
      'dark': 'Dark',
      'accent_color': 'Accent color',
      'accent_teal': 'Teal',
      'accent_blue': 'Blue',
      'accent_indigo': 'Indigo',
      'accent_purple': 'Purple',
      'accent_orange': 'Orange',
      'required_system_module': 'Required platform foundation',
      'status_ready': 'Ready',
      'status_foundation': 'Foundation',
      'status_planned': 'Planned',
      'status_deferred': 'Deferred',
      'system_group_foundation': 'Foundation',
      'system_group_experience': 'Experience & UI',
      'system_group_services': 'Shared Services',
      'system_group_platform': 'Platform Adapters',
      'system_group_developer': 'Developer Capabilities',
      'system_module_kernel': 'Kernel',
      'system_module_kernel_help': 'Application lifecycle, error boundaries, service registration and capability resolution.',
      'system_module_modules': 'Module & App Registry',
      'system_module_modules_help': 'Registers applications/modules, dependencies, manifests and enable/disable state.',
      'system_module_metadata': 'Metadata & DocTypes',
      'system_module_metadata_help': 'Metadata-driven DocTypes, fields, modules and customization contracts.',
      'system_module_documents': 'Documents',
      'system_module_documents_help': 'Generic document lifecycle, validation, links, child tables, submit/cancel and delete protection.',
      'system_module_data': 'Data & Persistence',
      'system_module_data_help': 'Structured storage, transactions, queries and migrations independent from business apps.',
      'system_module_methods': 'Method Modules',
      'system_module_methods_help': 'Global system/custom server code modules with validation, exports, dependencies and revisions.',
      'system_module_scripts': 'Scripts & Events',
      'system_module_scripts_help': 'Client/server script contracts, lifecycle hooks, validation and the future safe runtime.',
      'system_module_ui': 'UI Framework',
      'system_module_ui_help': 'Responsive shell, Form View, List View, dialogs and reusable application UI primitives.',
      'system_module_workspaces': 'Workspaces',
      'system_module_workspaces_help': 'Application navigation surfaces, shortcuts, quick lists and workspace registration.',
      'system_module_reports': 'Reporting',
      'system_module_reports_help': 'Generic Report Builder, native/query report contracts, filters and exports.',
      'system_module_files': 'Files & Attachments',
      'system_module_files_help': 'Cross-platform file, attachment, storage and sharing contracts.',
      'system_module_printing': 'Printing',
      'system_module_printing_help': 'Platform-independent printing/PDF contracts with Windows, mobile, web and server adapters.',
      'system_module_import_export': 'Import / Export',
      'system_module_import_export_help': 'Reusable CSV/XLSX import, export, templates and validation services.',
      'system_module_localization': 'Localization',
      'system_module_localization_help': 'Languages, RTL, locale-aware formatting and translation services.',
      'system_module_settings': 'Settings',
      'system_module_settings_help': 'System, application and user preference contracts.',
      'system_module_security': 'Security',
      'system_module_security_help': 'Optional users, roles, permissions and authentication for applications that need them.',
      'system_module_workflow': 'Workflow & Approvals',
      'system_module_workflow_help': 'Metadata-driven states, transitions, role approvals, safe conditions and workflow history.',
      'workflow_action': 'Workflow Action',
      'workflow_history': 'Workflow History',
      'workflow_comment': 'Comment',
      'workflow_apply': 'Apply',
      'system_module_scheduler': 'Scheduler & Jobs',
      'system_module_scheduler_help': 'Scheduled tasks, background jobs and queues for server-capable applications.',
      'system_module_audit': 'Audit & Versions',
      'system_module_audit_help': 'Audit history, document/system change records and version history.',
      'system_module_diagnostics': 'Logging & Diagnostics',
      'system_module_diagnostics_help': 'Structured system logs, runtime health snapshots and platform diagnostics independent from applications.',
      'system_module_notifications': 'Notifications',
      'system_module_notifications_help': 'Shared in-app, email, SMS and push notification contracts.',
      'system_module_sync': 'Sync & Offline',
      'system_module_sync_help': 'Local-first synchronization and conflict handling for multi-device applications.',
      'system_module_server': 'Server Platform',
      'system_module_server_help': 'API endpoints, tokens, PostgreSQL, server mode and background processing.',
      'system_module_mobile': 'Mobile Platform',
      'system_module_mobile_help': 'Permissions, contacts, SMS, sharing, camera and scanner capabilities for mobile apps.',
      'system_module_windows': 'Windows Platform',
      'system_module_windows_help': 'Printers, USB, serial, devices, filesystem and Windows integration capabilities.',
      'system_module_web': 'Web Platform',
      'system_module_web_help': 'Browser, storage, download and web-print adapters.',
      'system_module_developer': 'Developer Tools',
      'system_module_developer_help': 'DocType Studio, source parity, app conversion and development diagnostics.',
      'applications': 'Applications',
      'application_navigation': 'Application Navigation',
      'access_denied': 'Access denied',
      'route_not_found': 'Application route not found',
      'applications_help': 'Installed applications consume WMN capabilities without changing System Core.',
      'new_application': 'New Application',
      'application_id': 'Application ID',
      'application_title': 'Application Title',
      'version': 'Version',
      'minimum_platform_version': 'Minimum WMN Platform Version',
      'required_applications': 'Required Applications',
      'required_system_modules': 'Required System Modules',
      'required_capabilities': 'Required Capabilities',
      'optional_capabilities': 'Optional Capabilities',
      'capability_profile': 'Capability Profile',
      'incompatible': 'Incompatible',
      'warning': 'Warning',
      'error': 'Error',
      'application_modules': 'Application Modules',
      'application_workspaces': 'Application Workspaces',
      'application_routes': 'Application Routes',
      'application_permissions': 'Application Permissions',
      'metadata_contributions': 'Metadata Contributions',
      'platform_targets': 'Platform Targets',
      'publisher': 'Publisher',
      'license': 'License',
      'entry_route': 'Entry Route',
      'application_assets': 'Application Assets',
      'import_application_package': 'Import Package',
      'generate_package': 'Generate Package',
      'generate_application_package': 'Generate Application Package',
      'application_package_generated': 'Application package generated.',
      'application_package_installed': 'Application package installed.',
      'application_package_updated': 'Application package updated.',
      'package_components': 'Package Components',
      'package_validation_failed': 'Package Validation Failed',
      'package_validation_warnings': 'Package Validation Warnings',
      'build_history': 'Build History',
      'last_build': 'Last Build',
      'no_builds_yet': 'No application builds yet.',
      'install': 'Install',
      'continue_action': 'Continue',
      'application_registered': 'Application manifest registered.',
      'remove_application': 'Remove Application',
      'remove_application_confirm': 'Remove this WMN application manifest?',
      'no_applications_installed': 'No applications installed yet',
      'no_applications_installed_help': 'Create or import an application manifest. Its modules, DocTypes and Workspaces will appear without modifying the WMN platform.',
      'workspaces': 'Workspaces',
      'doctypes': 'DocTypes',
      'doctype_manager': 'DocType Manager',
      'doctype_studio': 'DocType Studio',
      'open_doctype_studio': 'Open Studio',
      'new_module': 'New Module',
      'module_saved': 'Module saved',
      'definition': 'Definition',
      'client_code': 'Client Code',
      'server_logic': 'Server Logic',
      'system_scripts_methods': 'System Scripts & Method Modules',
      'system_scripts_methods_help': 'Global platform code library. A Method is a server code module equivalent to a Frappe Python file and may export many callable functions. Scripts and Method modules are not owned by a DocType.',
      'system_method_modules': 'System Method Modules',
      'system_scripts': 'System Scripts / Hooks',
      'custom_method_modules': 'Custom Method Modules',
      'custom_scripts': 'Custom Scripts',
      'system_method_modules_help': 'Protected native/framework server modules. Each module groups its callable exports, for example wmn.db contains insert, update and delete. These modules are visible for inspection and parity tracking but are not editable.',
      'system_scripts_help': 'Global native system hooks/scripts are visible and protected. They are platform services, not DocType-owned scripts.',
      'custom_method_modules_help': 'Create a global custom server Method module using a custom.* namespace. The module is the WMN equivalent of a Python file and may contain many functions used by any DocType, script, report, workflow or other module.',
      'custom_scripts_help': 'Create global custom system scripts independent of any DocType. They are validated and revisioned here and remain activation-gated until the sandbox runtime is enabled.',
      'add_custom_method_module': 'Add Custom Method Module',
      'edit_custom_method_module': 'Edit Custom Method Module',
      'add_custom_script': 'Add Custom Script',
      'edit_custom_script': 'Edit Custom Script',
      'method_module_name': 'Module Namespace',
      'method_module_source': 'Server Method Module Source',
      'method_module_help': 'A Method is a complete server code module, not one function. It is equivalent to a Frappe Python module file. Public functions declared inside become module exports. Calls to wmn.* and custom.* modules are validated. Activation remains gated until the safe cross-platform runtime is completed.',
      'module_exports': 'exports',
      'module_dependencies': 'dependencies',
      'script_name': 'Script Name',
      'script_source': 'Script Source',
      'global_script_activation_help': 'Global custom scripts are validated and revisioned here. Activation remains gated until the cross-platform sandbox runtime is completed.',
      'delete_custom_script_confirm': 'Delete this custom system script?',
      'delete_custom_method_module_confirm': 'Delete this custom Method module?',
      'revision': 'Revision',
      'table_insert': 'Insert Into Table',
      'table_update': 'Update Table Row',
      'table_delete': 'Delete From Table',
      'safe_table_method_help': 'Safe CRUD functions are exports of system modules such as wmn.db and wmn.document. They never execute raw INSERT/UPDATE/DELETE SQL and always pass through DocType permissions, validation, naming, hooks and delete protection.',
      'scripts': 'scripts',
      'enable': 'Enable',
      'disable': 'Disable',
      'styles': 'Styles',
      'events_hooks': 'Events / Hooks',
      'permissions': 'Permissions',
      'source_parity': 'Source / Parity',
      'revisions': 'Revisions',
      'custom': 'Custom',
      'client_code_help': 'Editable per-DocType client source. Validation checks supported events, field references and blocked browser capabilities before the source can be considered ready.',
      'server_logic_help': 'Editable per-DocType server-hook source. It is validated against WMN/Frappe-compatible APIs and blocks raw SQL, process, file and direct ledger writes.',
      'doctype_studio_safety_help': 'DocType Studio stores code and style drafts inside the DocType metadata. It does not mutate native application controllers or physical schema. Activation stays gated until the matching sandbox/runtime is enabled.',
      'validate_code': 'Validate Code',
      'save_draft': 'Save Draft',
      'validate_and_save': 'Validate & Save',
      'activation_gated_help': 'Activation is disabled in this baseline so a draft cannot break the running application before the cross-platform sandbox/renderer is completed.',
      'form_style': 'Form Style',
      'list_style': 'List Style',
      'web_style': 'Web CSS',
      'validate_style': 'Validate Style',
      'native_style_help': 'WMN Form/List styles use a scoped Flutter-safe style DSL such as field(customer_name) { font-weight: bold; }. They are stored and validated without changing global UI styles.',
      'web_style_help': 'Web CSS is stored per DocType and validated to reject global or unsafe selectors. Print CSS remains part of Print Format, not DocType Studio.',
      'events_hooks_help': 'Supported document/form lifecycle events. Client and server code should use these names so the same lifecycle can be mapped to WMN native document hooks.',
      'no_permissions_defined': 'No explicit DocType permissions are defined.',
      'refresh_reference_source': 'Refresh Imported Reference Source',
      'source_parity_help': 'Reference source belongs to an imported application package and is loaded on demand only. WMN never executes it. Use it to compare external source with the WMN native controller and editable Studio draft.',
      'no_reference_source_loaded': 'No imported reference source is available for this DocType. Import an application package first, then refresh this view.',
      'no_revisions': 'No DocType Studio revisions yet.',
      'restore_revision': 'Restore as new draft',
      'revision_restored_as_draft': 'Revision restored as a new draft.',
      'validation_passed': 'Validation passed',
      'validation_failed': 'Validation failed',
      'reload': 'Reload',
      'reference_copied_to_draft': 'Reference source copied to Studio draft',
      'copy_to_client_draft': 'Copy to Client Draft',
      'copy_to_server_draft': 'Copy to Server Draft',
      'validate_doctype': 'Validate DocType',
      'doctype_valid': 'DocType definition is valid',
      'list_settings': 'List View Settings',
      'visible_columns': 'Visible Columns',
      'search_fields': 'Search Fields',
      'sort_descending': 'Descending Sort',
      'page_size': 'Page Size',
      'list_layout': 'List Layout',
      'table_layout': 'Table',
      'cards_layout': 'Cards',
      'hide_name_column': 'Hide Name Column',
      'new_doctype': 'New DocType',
      'edit_doctype': 'Edit DocType',
      'delete_doctype': 'Delete DocType',
      'delete_doctype_confirm': 'Delete this DocType and its physical table/data?',
      'doctype_still_referenced': 'DocType is still referenced',
      'doctype_name': 'DocType Name',
      'module_label': 'Module',
      'title_field': 'Title Field',
      'autoname': 'Autoname',
      'single_doctype': 'Single DocType',
      'child_doctype': 'Child DocType',
      'track_changes': 'Track Changes',
      'allow_create': 'Allow Create',
      'allow_edit': 'Allow Edit',
      'allow_delete': 'Allow Delete',
      'allow_import': 'Allow Import',
      'allow_export': 'Allow Export',
      'system_doctype': 'System DocType',
      'system_doctype_read_only': 'Core/System DocTypes are defined by the consolidated source baseline. Use customization metadata instead of mutating their physical schema here.',
      'physical_table': 'Physical Table',
      'new_field': 'New Field',
      'edit_field': 'Edit Field',
      'delete_field': 'Delete Field',
      'delete_field_confirm': 'Delete this field and its physical column/data?',
      'field_name': 'Field Name',
      'field_type': 'Field Type',
      'render_as': 'Render As',
      'render_as_help': 'Choose the UI control without changing the stored field type. AUTO uses metadata and safe inference.',
      'invalid_field_name': 'Field name must start with a letter/underscore and contain only letters, numbers, and underscores.',
      'field_type_storage_guard': 'Changing to a field type with a different SQL storage family is blocked to protect existing data.',
      'default_value': 'Default Value',
      'description': 'Description',
      'in_list_view': 'In List View',
      'standard_filter': 'Standard Filter',
      'searchable': 'Searchable',
      'allow_on_submit': 'Allow on Submit',
      'depends_on': 'Depends On',
      'mandatory_depends_on': 'Mandatory Depends On',
      'read_only_depends_on': 'Read Only Depends On',
      'fetch_from': 'Fetch From',
      'precision': 'Precision',
      'length': 'Length',
      'move_up': 'Move Up',
      'move_down': 'Move Down',
      'link_options_help': 'Enter the target DocType name.',
      'dynamic_link_options_help': 'Enter the fieldname that contains the target DocType.',
      'table_options_help': 'Enter a Child DocType name.',
      'select_options_help': 'Enter one option per line.',
      'submitted': 'Submitted',
      'cancelled': 'Cancelled',
      'cancel_document': 'Cancel Document',
      'cancel_document_confirm': 'Cancel this submitted document?',
      'search_desk': 'Search Workspaces and DocTypes',
      'workspace_navigation': 'Workspace Navigation',
      'workspace_shortcuts': 'Shortcuts',
      'workspace_links': 'Links',
      'workspace_not_found': 'Workspace not found',
      'page_not_found': 'Page not found',
      'page_metadata_ready': 'This page is ready for metadata content.',
      'page_controller_missing': 'The page controller is not installed on this runtime.',
      'page_target_unavailable': 'The page target is unavailable or not permitted.',
      'workspace_charts': 'Dashboard Charts',
      'workspace_quick_lists': 'Quick Lists',
      'workspace_quick_list': 'Quick List',
      'workspace_chart_requires_port': 'This chart needs a report/data-source port or has no local data yet.',
      'number_card': 'Number Card',
      'unknown_doctype': 'Unknown DocType',
      'invalid_link': 'Invalid link',
      'report_requires_porting': 'This imported report still requires porting',
      'report_available_in_reports': 'This report is available in Reports',
      'erpnext_v16_stack': 'ERPNext v16 + Frappe v16 Stack',
      'erpnext_stack_help': 'Recommended conversion preset. WMN downloads and converts Frappe v16 first, then ERPNext v16, so shared DocTypes and dependencies are available before ERPNext metadata is imported.',
      'download_erpnext_stack': 'Download and Convert ERPNext v16 Stack',
      'select_local_erpnext_stack': 'Select Local Frappe + ERPNext ZIPs',
      'local_stack_conversion_start': 'Starting local Frappe/ERPNext stack conversion…',
      'local_stack_conversion_complete': 'Local Frappe/ERPNext stack conversion finished.',
      'erpnext_stack_start': 'Starting ERPNext v16 stack conversion…',
      'frappe_core_downloading': 'Downloading and converting Frappe v16 core…',
      'erpnext_downloading': 'Downloading and converting ERPNext v16…',
      'erpnext_stack_complete': 'ERPNext v16 stack conversion finished. Review Porting Tasks for Python/controllers/hooks that require native WMN implementation.',
      'frappe_package_help': 'Convert a complete Frappe / ERPNext app ZIP into WMN metadata, Workspaces, DocTypes and tracked porting tasks.',
      'app_name_override': 'App Name Override',
      'optional': 'Optional',
      'convert_zip_app': 'Convert App ZIP',
      'convert_zip_help': 'Select a downloaded Frappe/ERPNext application ZIP. WMN scans metadata without executing Python.',
      'select_app_zip': 'Select App ZIP',
      'github_app_download': 'Download from GitHub',
      'github_repository': 'GitHub Repository',
      'git_ref': 'Branch / Ref',
      'download_and_convert': 'Download and Convert',
      'downloading_app': 'Downloading application package…',
      'converting_app': 'Converting application package…',
      'advanced_single_doctype_import': 'Advanced: Single DocType JSON',
      'converted_doctypes': 'Converted DocTypes',
      'converted_workspaces': 'Converted Workspaces',
      'converted_pages': 'Converted Pages',
      'placeholder_dependencies': 'Dependency Placeholders',
      'porting_tasks': 'Porting Tasks',
      'artifacts': 'Artifacts',
      'converted': 'Converted',
      'needs_port': 'Needs Port',
      'failed': 'Failed',
      'conversion_artifacts': 'Conversion Artifacts',
      'showing_first_500': 'Showing first 500 entries',
      'frappe_package_limitations': 'WMN never executes Frappe Python or arbitrary SQL. Unsupported controllers, hooks, reports, workflows and server scripts are preserved as porting tasks with their source paths.',
      'framework_foundation': 'Framework Foundation',
      'data_import_export': 'Data Import / Export',
      'data_import': 'Data Import',
      'data_export': 'Data Export',
      'doctype': 'DocType',
      'import_mode': 'Import Mode',
      'insert_new': 'Insert New',
      'update_existing': 'Update Existing',
      'upsert': 'Insert or Update',
      'copy_template': 'Copy CSV Template',
      'download_template': 'Download Template',
      'select_file': 'Select File',
      'fields': 'Fields',
      'import_records': 'Import Records',
      'rows_success': 'Successful Rows',
      'rows_failed': 'Failed Rows',
      'file_format': 'File Format',
      'export_records': 'Export Records',
      'selected_fields': 'Selected Fields',
      'save_file': 'Save File',
      'template_copied': 'Template copied',
      'frappe_app_import': 'External Frappe App Converter',
      'source_porting_workbench': 'Source Porting Workbench',
      'search_source_files': 'Search source files',
      'source_units': 'Source Units',
      'no_source_units': 'No source units found',
      'no_auto_conversion': 'No automatic conversion was generated for this source unit.',
      'conversion_status': 'Conversion Status',
      'conversion_strategy': 'Conversion Strategy',
      'confidence': 'Confidence',
      'diagnostics': 'Diagnostics',
      'dependencies': 'Dependencies',
      'open_source_porting_workbench': 'Open Source Porting Workbench',
      'imported_apps': 'Imported Apps',
      'frappe_import_help': 'Import Frappe DocType JSON metadata and convert it to native WMN DocTypes.',
      'source_app': 'Source App',
      'import_doctype_json': 'Import DocType JSON',
      'frappe_import_limitations': 'DocType metadata is converted automatically. Python controllers, hooks.py, arbitrary SQL and background jobs require explicit porting to WMN engines/scripts.',
      'search_doctype': 'Search DocTypes',
      'dynamic_doctype': 'Legacy Dynamic DocType',
      'physical_doctype': 'Physical DocType',
      'script_reports': 'Script Reports',
      'new_script_report': 'New Script Report',
      'script_report': 'Script Report',
      'reference_doctype': 'Reference DocType',
      'runtime_filters_json': 'Runtime Filters JSON',
      'columns_json': 'Columns JSON',
      'report_filters': 'Report Filters',
      'report_results': 'Report Results',
      'invalid_number': 'Invalid number',
      'invalid_json': 'Invalid JSON',
      'new_record': 'New Record',
      'quick_create': 'Quick Create',
      'manage_records': 'Manage Records',
      'submittable': 'Submittable',
      'filter': 'Filter',
      'clear_filters': 'Clear Filters',
      'id': 'ID',
      'open': 'Open',
      'delete_record_confirm': 'Delete this record?',
      'field': 'Field',
      'rate': 'Rate',
      'erp_home': 'ERP Home',
      'buying': 'Buying',
      'debit_account': 'Debit Account',
      'credit_account': 'Credit Account',
      'create_next': 'Create Next',
      'submit_document': 'Submit Document',
      'required_by': 'Required By',
      'source_document': 'Source Document',
      'receive_payment': 'Receive Payment',
      'internal_transfer': 'Internal Transfer',
      'new_payment_entry': 'New Payment Entry',
      'allocation': 'Allocation',
      'unallocated': 'Unallocated',
      'erpnext_reference': 'ERPNext Functional Reference',
      'functional_parity': 'Functional Parity',
      'procurement_flow': 'Procurement Flow',
      'selling_flow': 'Selling Flow',
      'inventory_flow': 'Inventory Flow',
      'module_status': 'Module Status',
      'operational': 'Operational',
      'foundation': 'Foundation',

      'receipt': 'Receipt',
      'grand_total': 'Grand Total',
      'payments': 'Payments',
      'print_job': 'Print Job',
      'selling_rate': 'Selling Rate',
      'allow_negative_stock': 'Allow Negative Stock',
      'tracked_by_batch': 'Tracked by Batch',
      'tracked_by_serial': 'Tracked by Serial',
      'barcode': 'Barcode',
      'add_barcode': 'Add Barcode',
      'unknown_barcode': 'Barcode was not recognized',
      'scan_barcode': 'Scan / Enter Barcode',
      'manual_discount_total': 'Manual Discount',
      'paid_amount': 'Paid Amount',
      'add_row': 'Add Row',
      'remove': 'Remove',
      'open_cash_session_first': 'Open a cash session first',
      'session_open': 'Cash session is open',
      'no_open_session': 'No open cash session',
      'new_pin_optional': 'New PIN (optional)',
      'display_name': 'Display Name',
      'connection_type': 'Connection Type',
      'network': 'Network',
      'serial': 'Serial',
      'windows_raw': 'Windows Raw',
      'qz': 'QZ Tray',
      'usb': 'USB',
      'bluetooth': 'Bluetooth',
      'system_print': 'System / PDF',
      'save_settings': 'Save Settings',
      'provider': 'Provider',
      'configuration_json': 'Configuration JSON',
      'generic_rest': 'Generic REST',
      'returned_qty': 'Returned Qty',
      'available_to_return': 'Available to Return',
      'condition_json': 'Conditions JSON',
      'action_json': 'Actions JSON',
      'enabled': 'Enabled',
      'details': 'Details',
      'status': 'Status',
      'date': 'Date',
      'count': 'Count',
      'app_name': 'WMN Application Platform',
      'items': 'Items',
      'rules': 'Commercial Rules',
      'reports': 'Reports',
      'system': 'System',
      'customization': 'Customization',
      'custom_fields': 'Custom Fields',
      'property_overrides': 'Property Overrides',
      'client_scripts': 'Client Scripts',
      'server_scripts': 'Server Scripts',
      'script_logs': 'Script Logs',
      'add_custom_field': 'Add Custom Field',
      'add_property_override': 'Add Property Override',
      'add_client_script': 'Add Client Script',
      'add_server_script': 'Add Server Script',
      'label': 'Label',
      'insert_after': 'Insert After',
      'options': 'Options',
      'required': 'Required',
      'read_only': 'Read Only',
      'hidden': 'Hidden',
      'script': 'Script',
      'event': 'Event',
      'property': 'Property',
      'run_test': 'Run Test',
      'script_success': 'Script executed successfully',
      'customization_help': 'Extend applications without changing WMN System Core.',
      'tax_id': 'Tax ID',
      'parent_group': 'Parent Group',
      'set_active': 'Set active',
      'users': 'Users',
      'add': 'Add',
      'create': 'Create',
      'edit': 'Edit',
      'delete': 'Delete',
      'disabled': 'Disabled',
      'search': 'Search',
      'no_records': 'No records found',
      'mobile': 'Mobile',
      'email': 'Email',
      'add_user': 'Add User',
      'edit_user': 'Edit User',
      'username': 'Username',
      'role': 'Role',
      'confirm_delete': 'Confirm Delete',
      'delete_or_disable_help': 'If this record is already used by transactions, WMN will disable it instead of breaking history.',
      'record_deleted': 'Record deleted.',
      'record_disabled_used': 'Record is used and was disabled instead of deleted.',
      'cannot_delete': 'Cannot delete',
      'edit_rule': 'Edit Rule',
      'all': 'All',
      'unpaid': 'Unpaid',
      'partly_paid': 'Partly Paid',
      'document_type': 'Document Type',
      'all_groups': 'All',
      'stock': 'Stock',
      'cart': 'Cart',
      'clear': 'Clear',
      'manual_discount': 'Manual Discount',
      'payment': 'Payment',
      'gross_total': 'Gross Total',
      'discounts': 'Discounts',
      'discount': 'Discount',
      'total': 'Total',
      'quantity': 'Quantity',
      'batch': 'Batch',
      'serial_numbers': 'Serial Numbers',
      'scan_or_enter_serials': 'Scan or enter serial numbers, one per line',
      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      'code': 'Code',
      'name': 'Name',
      'value': 'Value',
      'reason': 'Reason',
      'percentage': 'Percentage',
      'amount': 'Amount',
      'approve': 'Approve',
      'print': 'Print',
      'return': 'Return',
      'paid': 'Paid',
      'outstanding': 'Outstanding',
      'lifecycle': 'Lifecycle',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'appearance': 'Appearance',
      'theme_system': 'System',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'printing': 'Printing',
      'print_settings': 'Print Settings',
      'preview_only': 'Preview only',
      'windows_printer_share': 'Windows Raw Printer Share',
      'host': 'Host',
      'port': 'Port',
      'com_port': 'COM Port',
      'printer_path': 'Printer path',
      'cut_paper': 'Cut paper',
      'open_cash_drawer': 'Open cash drawer',
      'auto_print': 'Auto print after sale',
      'paper_width': 'Paper width',
      'print_job_sent': 'Print job sent.',
      'export_pdf': 'Export / Share PDF',
      'system_print_mode': 'System print layout',
      'receipt_layout': 'Receipt layout',
      'a4_layout': 'A4 layout',
      'barcode_structure': 'Barcode Structure',
      'add_barcode_structure': 'Add Barcode Structure',
      'edit_barcode_structure': 'Edit Barcode Structure',
      'prefix': 'Prefix',
      'quantity_start': 'Quantity start',
      'quantity_length': 'Quantity length',
      'quantity_divisor': 'Quantity divisor',
      'price_start': 'Price start',
      'price_length': 'Price length',
      'price_divisor': 'Price divisor',
      'add_gateway': 'Add Gateway',
      'edit_gateway': 'Edit Gateway',
      'test_gateway': 'Test Gateway',
      'generic_rest_lan': 'Generic REST / LAN',
      'geidea_rest': 'Geidea-compatible REST',
      'endpoint_url': 'Endpoint URL',
      'electronic_gateway': 'Electronic Gateway',
      'gateway_profile': 'Gateway Profile',
      'cash': 'Cash',
      'card': 'Card',
      'bank': 'Bank',
      'reference_no': 'Reference No.',
      'add_payment': 'Add Payment',
      'credit_sale': 'Credit sale',
      'credit_not_allowed': 'Credit and partial payment are disabled by the active POS Profile.',
      'remaining': 'Remaining',
      'add_rule': 'Add Rule',
      'priority': 'Priority',
      'rule_type': 'Rule Type',
      'apply_on': 'Apply On',
      'brand': 'Brand',
      'discount_percentage': 'Discount %',
      'discount_amount': 'Discount Amount',
      'fixed_rate': 'Fixed Rate',
      'min_qty': 'Minimum Qty',
      'min_amount': 'Minimum Amount',
      'buy_x_get_y': 'Buy X Get Y / Free Item',
      'free_qty': 'Free Qty',
      'supervisor': 'Supervisor',
      'pin': 'PIN',
      'edit_profile': 'Edit Profile',
      'company': 'Company',
      'branch': 'Branch',
      'currency': 'Currency',
      'allow_credit': 'Allow Credit',
      'yes': 'Yes',
      'no': 'No',
      'cash_session': 'Cash Session',
      'open_session': 'Open Session',
      'close_session': 'Close Session',
      'opening_cash': 'Opening Cash',
      'actual_cash': 'Actual Cash',
      'expected': 'Expected',
      'difference': 'Difference',
      'cash_movement': 'Cash Movement',
      'cash_in': 'Cash In',
      'cash_out': 'Cash Out',
      'note': 'Note',
      'ui_preferences': 'POS UI Preferences',
      'grid_view': 'Grid View',
      'button_view': 'Button View',
      'show_cart_counter': 'Show item cart counter',
      'auto_open_receipt': 'Open receipt after sale',
      'database': 'Database',
      'schema_version': 'Schema Version',
      'storage': 'Storage',
      'location': 'Location',
      'payment_method_summary': 'Payment Method Summary',
      'cash_movement_report': 'Cash Movement',
      'shift_closing_report': 'Shift Closing',
      'report_builder': 'Report Builder',
      'saved_reports': 'Saved Reports',
      'new_report': 'New Report',
      'edit_report': 'Edit Report',
      'run_report': 'Run Report',
      'show_report': 'Show Report',
      'print_preview': 'Print / Preview',
      'print_format': 'Print Format',
      'letter_head': 'Letter Head',
      'default_letter_head': 'Default / Automatic',
      'no_letter_head': 'No Letter Head',
      'print_language': 'Print Language',
      'refresh_preview': 'Refresh Preview',
      'print_template_help': 'WMN Print Template Tokens',
      'report_creation_guide': 'Report Creation Guide',
      'report_creation_intro': 'Choose a report type, then define Filters and Columns in the editable child tables below. Query/managed Script code is stored in Storage, and complete standard report definitions can be synchronized from an application report folder.',
      'report_builder_creation_help': 'Report Builder: choose a Reference DocType/source, then add Filters and Columns as table rows. No SQL is required.',
      'query_report_creation_help': 'Query Report: add Filters/Columns as table rows and edit one read-only SELECT/WITH query in the SQL editor. Use %(filter_name)s placeholders; WMN binds values and stores SQL in Storage.',
      'script_report_creation_help': 'Script Report: add Filters/Columns as table rows and use a registered NATIVE_HANDLER key or editable managed STORAGE_FILE source. The built-in example shows a real two-table JOIN.',
      'query_sql_code': 'Query SQL Code',
      'query_sql_code_help': 'The SQL source is shown here for learning/editing, but WMN stores it in Storage and keeps only the source path in the Report record.',
      'query_sql_required': 'Query SQL is required.',
      'script_source_code': 'Script Source Code',
      'native_handler_source_help': 'Native handlers are compiled Dart. Built-in examples show a read-only source preview so you can see the real logic used by the report.',
      'managed_script_source_help': 'Managed script source is stored outside the database in WMN Storage.',
      'native_handler_source_preview': 'Native Handler Source Preview',
      'managed_script_source': 'Managed Script Source',
      'native_handler_key': 'Native Handler Key',
      'source_path': 'Source Path',
      'script_source_required': 'Script source is required.',
      'script_storage_unavailable': 'Script Storage is unavailable.',
      'report_example_guide': 'Working Example Report',
      'select_doctype_first': 'Select the target DocType first',
      'how_to_create': 'How to create it',
      'report_name_required': 'Report name is required.',
      'report_reference_doctype_required': 'Reference DocType is required for Report Builder.',
      'report_columns_required': 'Add at least one report column.',
      'delete_report': 'Delete Report',
      'report_name': 'Report Name',
      'data_source': 'Data Source',
      'report_columns': 'Report Columns',
      'filters': 'Filters',
      'add_filter': 'Add Filter',
      'operator': 'Operator',
      'aggregation': 'Aggregation',
      'sort_by': 'Sort By',
      'sort_direction': 'Sort Direction',
      'ascending': 'Ascending',
      'descending': 'Descending',
      'row_limit': 'Row Limit',
      'copy_csv': 'Copy CSV',
      'csv_copied': 'CSV copied to clipboard.',
      'report_saved': 'Report saved.',
      'report_deleted': 'Report deleted.',
      'select_columns': 'Select at least one column.',
      'no_saved_reports': 'No custom reports yet.',
      'report_builder_help': 'Build reports without SQL. Select fields, filters, grouping and aggregates.',
      'report_rows': 'Rows',
      'report_duration': 'Duration',
      'milliseconds': 'ms',
      'none': 'None',
      'equals': 'Equals',
      'not_equals': 'Not equals',
      'greater_than': 'Greater than',
      'greater_or_equal': 'Greater or equal',
      'less_than': 'Less than',
      'less_or_equal': 'Less or equal',
      'contains': 'Contains',
      'starts_with': 'Starts with',
      'is_empty': 'Is empty',
      'is_not_empty': 'Is not empty',
      'printer_name': 'Printer name / path',
      'qz_printer_name': 'QZ printer name',
      'usb_device_name': 'USB device name',
      'usb_vendor_id': 'USB Vendor ID',
      'usb_product_id': 'USB Product ID',
      'bluetooth_name': 'Bluetooth device name',
      'bluetooth_address': 'Bluetooth address',
      'preview': 'Preview',
      'serial_com': 'ESC/POS Serial / COM',
      'windows_raw_label': 'Windows Raw',
      'usb_adapter': 'USB Adapter',
      'bluetooth_adapter': 'Bluetooth Adapter',
      'camera_scan': 'Camera Scan',
      'camera_scan_hint': 'Point the camera at a barcode or QR code',
      'camera_error': 'Camera error',
      'barcode_added': 'Barcode added',
      'scanning': 'Scanning...',
      'capture_scan': 'Capture and scan',
      'no_rules_yet': 'No rules yet.',
      'if_label': 'IF',
      'do_label': 'DO',
      'uses': 'Uses',
      'conditions': 'Conditions',
      'actions': 'Actions',
      'max_uses_optional': 'Max uses (optional)',
      'advanced_rule_help': 'Advanced rule options: item/item group/brand/UOM, quantity and amount thresholds, fixed rate, percentage/amount discount, multiple rules, discount on discounted rate, transaction rules, coupon-linked rules, cumulative rules, product discount and free items.',
      'no_data': 'No data',
      'available': 'Available',
      'prefix_label': 'Prefix',
      'item_segment': 'item segment',
      'test_provider': 'Test',
      'generic_rest_provider': 'Generic REST/LAN',
      'geidea_compatibility': 'Geidea compatibility',
      'stc_compatibility': 'STC SoftPOS compatibility',
      'more': 'More',
      'view_cart': 'View Cart',
      'cart_empty': 'Cart is empty',
      'rule_scope': 'Applies To',
      'target': 'Target',
      'benefit': 'Benefit',
      'validity': 'Validity',
      'advanced_options_preserved': 'Advanced options from this rule are preserved internally even though they are not shown as raw JSON.',
      'basic_information': 'Basic Information',
      'whole_transaction': 'Whole Transaction',
      'benefit_type': 'Benefit Type',
      'max_qty': 'Maximum Qty',
      'max_amount': 'Maximum Amount',
      'cumulative_rule': 'Cumulative Rule',
      'cumulative_rule_help': 'Use previous eligible customer purchases when evaluating this rule.',
      'buy_qty': 'Buy Qty',
      'max_discount_optional': 'Maximum Discount (optional)',
      'stackable': 'Can combine with other rules',
      'stackable_help': 'Allow another eligible pricing/promotion rule to apply in the same transaction.',
      'valid_from': 'Valid From',
      'valid_upto': 'Valid Until',
      'name_required': 'Name or code is required.',
      'max_uses': 'Maximum Uses',
      'refresh': 'Refresh',
    },
    'ar': {
      'frappe_runtime': 'محرك WMN المكافئ لـ Frappe',
      'frappe_runtime_native_help': 'ينفذ WMN عقود ووظائف إطار Frappe بشكل أصلي. مصدر Frappe مرجع وظيفي وليس اعتماد تشغيل داخل WMN.',
      'frappe_api_compatibility': 'توافق واجهات Frappe البرمجية',
      'api_weighted_coverage': 'التغطية المرجحة للواجهات',
      'runtime_engines': 'محركات وقت التشغيل',
      'source_api': 'واجهة Frappe',
      'target_api': 'المكافئ في WMN',
      'current_user': 'المستخدم الحالي',
      'roles': 'الأدوار',
      'queued_jobs': 'المهام المنتظرة',
      'failed_jobs': 'المهام الفاشلة',
      'desk': 'المكتب / إطار العمل',
      'application_platform': 'منصة التطبيقات',
      'home': 'الرئيسية',
      'current_ui': 'الواجهة الحالية',
      'workspace_ui': 'واجهة مساحات العمل',
      'workspace_home_title': 'مساحات العمل',
      'workspace_home_description': 'افتح مساحة العمل التي تحتاجها فقط. أدوات النظام والإدارة والتطوير والتطبيقات تبقى منظمة داخل مساحات العمل الخاصة بها.',
      'workspace_system': 'النظام',
      'workspace_administration': 'الإدارة',
      'workspace_developer': 'التطوير',
      'quick_start': 'بدء سريع',
      'platform_home_headline': 'ابنِ أي تطبيق فوق أساس WMN واحد ونظيف',
      'platform_home_description': 'توفر WMN قدرات نظام قابلة لإعادة الاستخدام، ومستندات مبنية على الميتاداتا، ومساحات عمل ومحولات للمنصات حتى يمكن إنشاء التطبيقات المستقبلية بدون إعادة بناء الأساس.',
      'platform_home_doctypes_help': 'صمم أنواع مستندات وحقول وسلوك مستندات قابلة لإعادة الاستخدام.',
      'platform_home_methods_help': 'أدر موديولات الميثودز العامة والسكربتات والتحقق والإصدارات.',
      'platform_home_modules_help': 'راجع قدرات النظام المتاحة للتطبيقات وفعّل ما تحتاجه فقط.',
      'platform_no_workspaces_help': 'لا توجد مساحات عمل لتطبيقات مثبتة بعد. يمكن لأي تطبيق مستقبلي تسجيل مساحات العمل الخاصة به بدون تعديل WMN Core.',
      'system_modules': 'موديولات النظام',
      'system_modules_help': 'قدرات نظام WMN مستقلة عن تطبيقات الأعمال. تبقى موديولات الأساس الإلزامية مفعلة، ويمكن تشغيل القدرات الاختيارية فقط عندما يحتاجها التطبيق.',
      'system_services': 'خدمات النظام',
      'platform_adapters': 'محولات المنصات',
      'current_platform': 'المنصة الحالية',
      'active_adapters': 'المحولات النشطة',
      'platform_capabilities': 'قدرات المنصة',
      'platform_services': 'خدمات المنصة',
      'system_module': 'موديول النظام',
      'system_services_help': 'مركز عام لمراجعة ملفات WMN والمهام والإشعارات والسجلات والتدقيق والإعدادات وصحة وقت التشغيل بدون ربطها بأي تطبيق أعمال.',
      'overview': 'نظرة عامة',
      'files': 'الملفات',
      'jobs': 'المهام',
      'logs': 'السجلات',
      'notifications': 'الإشعارات',
      'audit': 'التدقيق',
      'unread_notifications': 'الإشعارات غير المقروءة',
      'error_logs': 'سجلات الأخطاء',
      'pending_print_jobs': 'مهام الطباعة المنتظرة',
      'configuration_entries': 'إعدادات النظام',
      'audit_entries': 'سجلات التدقيق',
      'runtime_health': 'صحة وقت التشغيل',
      'kernel_state': 'حالة النواة',
      'storage_kind': 'نوع التخزين',
      'capture_diagnostics': 'التقاط حالة التشخيص',
      'scheduler_jobs': 'الجدولة والمهام الخلفية',
      'enqueue_due_schedules': 'إضافة المجدول المستحق للطابور',
      'run_next_job': 'تشغيل المهمة التالية',
      'schedules': 'الجداول الزمنية',
      'no_jobs': 'لا توجد مهام نظام في الطابور حتى الآن.',
      'no_files': 'لا توجد ملفات أو مرفقات مخزنة في المنصة حتى الآن.',
      'no_notifications': 'لا توجد إشعارات.',
      'mark_read': 'تحديد كمقروء',
      'no_logs': 'لا توجد سجلات نظام.',
      'no_audit_entries': 'لا توجد سجلات تدقيق.',
      'configuration': 'الإعدادات المنظمة',
      'add_setting': 'إضافة إعداد',
      'scope': 'النطاق',
      'scope_key': 'مفتاح النطاق',
      'setting_key': 'مفتاح الإعداد',
      'setting_value': 'قيمة الإعداد',
      'secret': 'قيمة سرية',
      'add_file': 'إضافة ملف',
      'file_content_mode': 'طريقة حفظ محتوى الملف',
      'managed_storage': 'التخزين المُدار',
      'managed_storage_help': 'نسخ الملف إلى WMN Storage وإدارة دورة حياته داخل المنصة.',
      'external_reference': 'مرجع خارجي',
      'external_reference_help': 'إبقاء الملف في مكانه وحفظ المرجع فقط. الإتاحة تعتمد على محول المنصة.',
      'external_reference_unavailable': 'المراجع الخارجية للملفات غير متاحة على هذه المنصة.',
      'export_file': 'تصدير الملف',
      'file_export_unsupported': 'تصدير الملف غير متاح على هذه المنصة.',
      'attachments': 'المرفقات',
      'add_attachment': 'إضافة مرفق',
      'no_attachments': 'لا توجد مرفقات مرتبطة بهذا السجل.',
      'detach_attachment': 'إلغاء ربط المرفق',
      'no_configuration_entries': 'لا توجد إعدادات منظمة معرفة حتى الآن.',
      'enabled_modules': 'الموديولات المفعلة',
      'ready_modules': 'الموديولات الجاهزة',
      'build': 'البناء',
      'developer_tools': 'أدوات المطور',
      'developer_center': 'مركز المطور',
      'developer_center_help': 'يعرض نواة WMN وسجل الخدمات والقدرات واعتماديات موديولات النظام وتعريفات التطبيقات ونقاط التوسعة الأصلية في مكان واحد.',
      'capability_registry': 'سجل القدرات',
      'capability_profiles': 'ملفات القدرات',
      'system_module_dependencies': 'اعتماديات موديولات النظام',
      'system_doctype_runtime_ownership': 'ملكية تشغيل DocTypes النظام',
      'runtime_owner': 'محرك التشغيل المالك',
      'runtime_kind': 'نوع التشغيل',
      'generic_editing_allowed': 'السماح بالتعديل العام',
      'application_manifests': 'تعريفات التطبيقات',
      'extension_points': 'نقاط التوسعة',
      'registered_services': 'الخدمات المسجلة',
      'available_capabilities': 'القدرات المتاحة',
      'provided_by': 'توفرها',
      'no_dependencies': 'لا توجد اعتماديات نظام',
      'system_depends_on': 'يعتمد على',
      'kernel_healthy': 'النواة سليمة',
      'kernel_degraded': 'النواة تحتاج مراجعة',
      'capability_available': 'متاحة',
      'capability_disabled': 'معطلة',
      'capability_unavailable': 'غير متاحة',
      'module_has_enabled_dependents': 'لا يمكن تعطيل هذا الموديول لأنه مطلوب من موديول نظام آخر مفعّل.',
      'app_converter': 'محول التطبيقات',
      'compatibility_runtime': 'محرك التوافق',
      'platform_settings': 'إعدادات المنصة',
      'feature_management': 'الميزات والخطط',
      'feature_management_help': 'لا تعمل الميزات الاختيارية إلا إذا كانت مشمولة في الخطة أو الترخيص واخترت أنت تفعيلها. ميزات المنصة الأساسية لا يمكن تعطيلها.',
      'feature_core_included': 'أساسية • مشمولة',
      'feature_not_entitled': 'غير مشمولة في الاستحقاق الحالي',
      'global_search': 'ابحث في مساحات العمل ومسارات التطبيقات وأنواع المستندات والموديولات',
      'no_search_results': 'لم يتم العثور على مساحة عمل أو مسار تطبيق أو نوع مستند أو موديول مطابق.',
      'expand_sidebar': 'توسيع الشريط الجانبي',
      'collapse_sidebar': 'طي الشريط الجانبي',
      'shell_layout': 'تخطيط الواجهة',
      'compact_navigation': 'تنقل مضغوط',
      'compact_navigation_help': 'يقلل ارتفاع عناصر التنقل مع بقاء نفس القدرات.',
      'show_workspace_labels': 'إظهار أسماء مساحات العمل',
      'light': 'فاتح',
      'dark': 'داكن',
      'accent_color': 'لون الواجهة',
      'accent_teal': 'تركوازي',
      'accent_blue': 'أزرق',
      'accent_indigo': 'نيلي',
      'accent_purple': 'بنفسجي',
      'accent_orange': 'برتقالي',
      'required_system_module': 'جزء إلزامي من أساس المنصة',
      'status_ready': 'جاهز',
      'status_foundation': 'أساس',
      'status_planned': 'مخطط',
      'status_deferred': 'مؤجل',
      'system_group_foundation': 'الأساس',
      'system_group_experience': 'الواجهة وتجربة الاستخدام',
      'system_group_services': 'الخدمات المشتركة',
      'system_group_platform': 'محولات المنصات',
      'system_group_developer': 'قدرات المطور',
      'system_module_kernel': 'النواة',
      'system_module_kernel_help': 'دورة تشغيل التطبيق وحدود الأخطاء وتسجيل الخدمات وحل القدرات.',
      'system_module_modules': 'سجل الموديولات والتطبيقات',
      'system_module_modules_help': 'يسجل التطبيقات والموديولات والاعتماديات والـManifest وحالة التفعيل.',
      'system_module_metadata': 'الميتاداتا والدوكتايبس',
      'system_module_metadata_help': 'أنواع المستندات والحقول والموديولات والتخصيصات المبنية على الميتاداتا.',
      'system_module_documents': 'المستندات',
      'system_module_documents_help': 'دورة مستند عامة والتحقق والروابط والجداول الفرعية والتقديم والإلغاء وحماية المسح.',
      'system_module_data': 'البيانات والتخزين',
      'system_module_data_help': 'تخزين ومعاملات واستعلامات وترحيلات منظمة ومستقلة عن تطبيقات الأعمال.',
      'system_module_methods': 'موديولات الميثودز',
      'system_module_methods_help': 'موديولات كود خادم عامة للنظام أو مخصصة مع التحقق والتصدير والاعتماديات والإصدارات.',
      'system_module_scripts': 'السكربتات والأحداث',
      'system_module_scripts_help': 'عقود سكربتات العميل والخادم والـHooks والتحقق ومحرك التنفيذ الآمن المستقبلي.',
      'system_module_ui': 'إطار الواجهة',
      'system_module_ui_help': 'واجهة مرنة وForm View وList View وحوارات ومكونات قابلة لإعادة الاستخدام.',
      'system_module_workspaces': 'مساحات العمل',
      'system_module_workspaces_help': 'واجهات تنقل التطبيقات والاختصارات والقوائم السريعة وتسجيل مساحات العمل.',
      'system_module_reports': 'التقارير',
      'system_module_reports_help': 'Report Builder عام وعقود التقارير الأصلية والاستعلامية والفلاتر والتصدير.',
      'system_module_files': 'الملفات والمرفقات',
      'system_module_files_help': 'عقود ملفات ومرفقات وتخزين ومشاركة تعمل عبر المنصات.',
      'system_module_printing': 'الطباعة',
      'system_module_printing_help': 'عقود طباعة وPDF مستقلة عن المنصة مع محولات لويندوز والموبايل والويب والسيرفر.',
      'system_module_import_export': 'الاستيراد والتصدير',
      'system_module_import_export_help': 'خدمات CSV وXLSX والقوالب والتحقق القابلة لإعادة الاستخدام.',
      'system_module_localization': 'الترجمة والتوطين',
      'system_module_localization_help': 'اللغات وRTL والتنسيق حسب اللغة وخدمات الترجمة.',
      'system_module_settings': 'الإعدادات',
      'system_module_settings_help': 'عقود إعدادات النظام والتطبيق وتفضيلات المستخدم.',
      'system_module_security': 'الأمان',
      'system_module_security_help': 'مستخدمون وأدوار وصلاحيات ومصادقة اختيارية للتطبيقات التي تحتاجها.',
      'system_module_workflow': 'سير العمل والموافقات',
      'system_module_workflow_help': 'حالات وانتقالات وموافقات حسب الأدوار وشروط آمنة وسجل كامل لسير العمل.',
      'workflow_action': 'إجراء سير العمل',
      'workflow_history': 'سجل سير العمل',
      'workflow_comment': 'ملاحظة',
      'workflow_apply': 'تنفيذ',
      'system_module_scheduler': 'الجدولة والمهام',
      'system_module_scheduler_help': 'مهام مجدولة ومعالجة خلفية وطوابير للتطبيقات التي تستخدم وضع السيرفر.',
      'system_module_audit': 'التدقيق والإصدارات',
      'system_module_audit_help': 'سجل التدقيق وتغييرات المستندات والنظام وسجل الإصدارات.',
      'system_module_diagnostics': 'السجلات والتشخيص',
      'system_module_diagnostics_help': 'سجلات نظام منظمة ولقطات لصحة وقت التشغيل وتشخيص للمنصة مستقل عن التطبيقات.',
      'system_module_notifications': 'الإشعارات',
      'system_module_notifications_help': 'عقود عامة للإشعارات داخل التطبيق والبريد والرسائل والدفع.',
      'system_module_sync': 'المزامنة والأوفلاين',
      'system_module_sync_help': 'مزامنة Local-first ومعالجة التعارضات لتطبيقات متعددة الأجهزة.',
      'system_module_server': 'منصة السيرفر',
      'system_module_server_help': 'واجهات API والتوكنز وPostgreSQL ووضع السيرفر والمعالجة الخلفية.',
      'system_module_mobile': 'منصة الموبايل',
      'system_module_mobile_help': 'الصلاحيات والكونتاكتس والرسائل والمشاركة والكاميرا والماسح لتطبيقات الموبايل.',
      'system_module_windows': 'منصة ويندوز',
      'system_module_windows_help': 'الطابعات وUSB وSerial والأجهزة والملفات والتكامل مع ويندوز.',
      'system_module_web': 'منصة الويب',
      'system_module_web_help': 'محولات المتصفح والتخزين والتنزيل والطباعة على الويب.',
      'system_module_developer': 'أدوات المطور',
      'system_module_developer_help': 'DocType Studio ومقارنة المصادر وتحويل التطبيقات وأدوات التشخيص.',
      'applications': 'التطبيقات',
      'application_navigation': 'تنقل التطبيقات',
      'access_denied': 'غير مصرح بالوصول',
      'route_not_found': 'مسار التطبيق غير موجود',
      'applications_help': 'التطبيقات المثبتة تستهلك قدرات WMN دون تعديل نواة النظام.',
      'new_application': 'تطبيق جديد',
      'application_id': 'معرف التطبيق',
      'application_title': 'اسم التطبيق',
      'version': 'الإصدار',
      'minimum_platform_version': 'أدنى إصدار مطلوب من منصة WMN',
      'required_applications': 'التطبيقات المطلوبة',
      'required_system_modules': 'موديولات النظام المطلوبة',
      'required_capabilities': 'القدرات المطلوبة',
      'optional_capabilities': 'القدرات الاختيارية',
      'capability_profile': 'ملف القدرات',
      'incompatible': 'غير متوافق',
      'warning': 'تحذير',
      'error': 'خطأ',
      'application_modules': 'موديولات التطبيق',
      'application_workspaces': 'مساحات عمل التطبيق',
      'application_routes': 'مسارات التطبيق',
      'application_permissions': 'صلاحيات التطبيق',
      'metadata_contributions': 'إضافات الميتاداتا',
      'platform_targets': 'المنصات المستهدفة',
      'publisher': 'الناشر',
      'license': 'الترخيص',
      'entry_route': 'مسار الدخول',
      'application_assets': 'أصول التطبيق',
      'import_application_package': 'استيراد حزمة تطبيق',
      'generate_package': 'توليد الحزمة',
      'generate_application_package': 'توليد حزمة التطبيق',
      'application_package_generated': 'تم توليد حزمة التطبيق.',
      'application_package_installed': 'تم تثبيت حزمة التطبيق.',
      'application_package_updated': 'تم تحديث حزمة التطبيق.',
      'package_components': 'مكونات الحزمة',
      'package_validation_failed': 'فشل التحقق من الحزمة',
      'package_validation_warnings': 'تحذيرات التحقق من الحزمة',
      'build_history': 'سجل البناء',
      'last_build': 'آخر بناء',
      'no_builds_yet': 'لا توجد عمليات بناء للتطبيق بعد.',
      'install': 'تثبيت',
      'continue_action': 'متابعة',
      'application_registered': 'تم تسجيل تعريف التطبيق.',
      'remove_application': 'إزالة التطبيق',
      'remove_application_confirm': 'هل تريد إزالة تعريف تطبيق WMN هذا؟',
      'no_applications_installed': 'لا توجد تطبيقات مثبتة بعد',
      'no_applications_installed_help': 'أنشئ أو استورد App Manifest؛ ستظهر الموديولات والدوكتايبس ومساحات العمل دون تعديل منصة WMN.',
      'workspaces': 'مساحات العمل',
      'doctypes': 'أنواع المستندات',
      'doctype_manager': 'إدارة أنواع المستندات',
      'doctype_studio': 'استوديو الدوكتايب',
      'open_doctype_studio': 'فتح الاستوديو',
      'new_module': 'موديول جديد',
      'module_saved': 'تم حفظ الموديول',
      'definition': 'التعريف',
      'client_code': 'كود العميل',
      'server_logic': 'منطق الخادم',
      'system_scripts_methods': 'إدارة سكربتات وموديولات الميثودز',
      'system_scripts_methods_help': 'مكتبة أكواد عامة على مستوى المنصة. المقصود بالميثود هو موديول كود خادم كامل يعادل ملف Python في Frappe ويمكن أن يحتوي عدة دوال عامة. السكربتات وموديولات الميثودز ليست مملوكة لدوكتايب محدد.',
      'system_method_modules': 'موديولات ميثودز النظام',
      'system_scripts': 'سكربتات / Hooks النظام',
      'custom_method_modules': 'موديولات الميثودز المخصصة',
      'custom_scripts': 'السكربتات المخصصة',
      'system_method_modules_help': 'موديولات الخادم الأصلية وإطار العمل محمية من التعديل. كل موديول يجمع الدوال العامة التي يصدرها؛ مثال: wmn.db يحتوي insert وupdate وdelete. تظهر للفحص ومتابعة المطابقة.',
      'system_scripts_help': 'تظهر سكربتات وHooks النظام العامة الأصلية بشكل محمي. وهي خدمات على مستوى المنصة وليست سكربتات مملوكة لدوكتايب محدد.',
      'custom_method_modules_help': 'يمكن إنشاء موديول ميثود خادم عام ضمن namespace يبدأ بـ custom. وهو المقابل داخل WMN لملف Python ويمكن أن يحتوي عدة دوال يستدعيها أي DocType أو Script أو Report أو Workflow أو موديول آخر.',
      'custom_scripts_help': 'يمكن إنشاء سكربتات نظام مخصصة عامة غير مرتبطة بأي DocType. يتم فحصها وحفظ إصداراتها هنا ويبقى تفعيلها مقفلاً حتى اكتمال الـSandbox Runtime.',
      'add_custom_method_module': 'إضافة موديول ميثود مخصص',
      'edit_custom_method_module': 'تعديل موديول الميثود المخصص',
      'add_custom_script': 'إضافة سكربت مخصص',
      'edit_custom_script': 'تعديل السكربت المخصص',
      'method_module_name': 'Namespace الموديول',
      'method_module_source': 'كود موديول الميثود على الخادم',
      'method_module_help': 'الميثود هنا موديول كود خادم كامل وليست دالة واحدة، وهي تعادل ملف Python في Frappe. الدوال العامة داخله تصبح Exports للموديول، ويتم فحص استدعاءات wmn.* وcustom.*. يبقى التفعيل مقفلاً حتى اكتمال Runtime الآمن متعدد المنصات.',
      'module_exports': 'الدوال العامة',
      'module_dependencies': 'الاعتماديات',
      'script_name': 'اسم السكربت',
      'script_source': 'مصدر السكربت',
      'global_script_activation_help': 'يتم فحص السكربتات العامة المخصصة وحفظ إصداراتها هنا، ويبقى التفعيل مقفلاً حتى اكتمال Sandbox Runtime متعدد المنصات.',
      'delete_custom_script_confirm': 'هل تريد حذف سكربت النظام المخصص هذا؟',
      'delete_custom_method_module_confirm': 'هل تريد حذف موديول الميثود المخصص هذا؟',
      'revision': 'الإصدار',
      'table_insert': 'Insert Into Table',
      'table_update': 'Update Table Row',
      'table_delete': 'Delete From Table',
      'safe_table_method_help': 'دوال CRUD الآمنة هي Exports من موديولات نظام عامة مثل wmn.db وwmn.document، ولا تنفذ SQL خامًا بل تمر عبر الصلاحيات والتحقق والتسمية والـHooks وحماية الحذف.',
      'scripts': 'سكربت',
      'enable': 'تفعيل',
      'disable': 'تعطيل',
      'styles': 'التنسيقات',
      'events_hooks': 'الأحداث / Hooks',
      'permissions': 'الصلاحيات',
      'source_parity': 'المصدر / المطابقة',
      'revisions': 'الإصدارات',
      'custom': 'مخصص',
      'client_code_help': 'كود عميل قابل للتعديل لكل دوكتايب. يتم فحص الأحداث والحقول والقدرات المحظورة قبل اعتباره جاهزًا.',
      'server_logic_help': 'منطق خادم قابل للتعديل لكل دوكتايب. يتم فحصه مقابل واجهات WMN/Frappe المتوافقة ومنع SQL الخام والوصول للنظام والكتابة المباشرة في دفاتر الأستاذ.',
      'doctype_studio_safety_help': 'يحفظ استوديو الدوكتايب مسودات الأكواد والتنسيقات داخل Metadata الخاصة بالدوكتايب دون تغيير محرك ERP الأصلي أو الـSchema الفيزيائي. يبقى التفعيل مقفلاً حتى يكتمل Runtime الآمن المقابل.',
      'validate_code': 'فحص الكود',
      'save_draft': 'حفظ كمسودة',
      'validate_and_save': 'فحص وحفظ',
      'activation_gated_help': 'التفعيل معطل في هذا الإصدار حتى لا تؤثر مسودة غير آمنة على ERP قبل اكتمال الـSandbox/Renderer متعدد المنصات.',
      'form_style': 'تنسيق الفورم',
      'list_style': 'تنسيق القائمة',
      'web_style': 'CSS للويب',
      'validate_style': 'فحص التنسيق',
      'native_style_help': 'تستخدم تنسيقات Form/List لغة WMN آمنة ومحددة النطاق لـFlutter مثل field(customer_name) { font-weight: bold; }، وتُحفظ وتُفحص دون تغيير التنسيق العام للتطبيق.',
      'web_style_help': 'يُحفظ Web CSS لكل دوكتايب ويُفحص لمنع المحددات العامة أو غير الآمنة. CSS الخاص بالطباعة يبقى ضمن Print Format وليس داخل DocType Studio.',
      'events_hooks_help': 'أحداث دورة حياة المستند والفورم المدعومة. يجب استخدام هذه الأسماء في كود العميل والخادم حتى يمكن مطابقتها مع Hooks الأصلية في WMN.',
      'no_permissions_defined': 'لا توجد صلاحيات صريحة معرفة لهذا الدوكتايب.',
      'refresh_reference_source': 'تحديث المصدر المرجعي المستورد',
      'source_parity_help': 'يتم تحميل المصدر المرجعي عند الطلب فقط ولا يتم تنفيذه داخل WMN. يستخدم للمقارنة بين JavaScript/Python الأصلي ومحرك WMN الأصلي ومسودة الاستوديو القابلة للتعديل.',
      'no_reference_source_loaded': 'لم يتم تحميل مصدر مرجعي لهذا الدوكتايب. استخدم الزر أعلاه للبحث داخل حزم Frappe/ERPNext المدمجة.',
      'no_revisions': 'لا توجد إصدارات محفوظة في استوديو الدوكتايب حتى الآن.',
      'restore_revision': 'استعادة كمسودة جديدة',
      'revision_restored_as_draft': 'تمت استعادة الإصدار كمسودة جديدة.',
      'validation_passed': 'نجح الفحص',
      'validation_failed': 'فشل الفحص',
      'reload': 'إعادة تحميل',
      'reference_copied_to_draft': 'تم نسخ المصدر المرجعي إلى مسودة الاستوديو',
      'copy_to_client_draft': 'نسخ إلى مسودة كود العميل',
      'copy_to_server_draft': 'نسخ إلى مسودة منطق الخادم',
      'validate_doctype': 'التحقق من نوع المستند',
      'doctype_valid': 'تعريف نوع المستند سليم',
      'list_settings': 'إعدادات عرض القائمة',
      'visible_columns': 'الأعمدة الظاهرة',
      'search_fields': 'حقول البحث',
      'sort_descending': 'ترتيب تنازلي',
      'page_size': 'حجم الصفحة',
      'list_layout': 'تخطيط القائمة',
      'table_layout': 'جدول',
      'cards_layout': 'بطاقات',
      'hide_name_column': 'إخفاء عمود الاسم',
      'new_doctype': 'نوع مستند جديد',
      'edit_doctype': 'تعديل نوع المستند',
      'delete_doctype': 'حذف نوع المستند',
      'delete_doctype_confirm': 'هل تريد حذف نوع المستند مع جدوله الفعلي وبياناته؟',
      'doctype_still_referenced': 'نوع المستند ما زال مستخدمًا كمرجع',
      'doctype_name': 'اسم نوع المستند',
      'module_label': 'الموديول',
      'title_field': 'حقل العنوان',
      'autoname': 'التسمية التلقائية',
      'single_doctype': 'نوع مستند مفرد',
      'child_doctype': 'نوع مستند فرعي',
      'track_changes': 'تتبع التغييرات',
      'allow_create': 'السماح بالإنشاء',
      'allow_edit': 'السماح بالتعديل',
      'allow_delete': 'السماح بالحذف',
      'allow_import': 'السماح بالاستيراد',
      'allow_export': 'السماح بالتصدير',
      'system_doctype': 'نوع مستند نظامي',
      'system_doctype_read_only': 'أنواع المستندات الأساسية/النظامية تُدار من الـSource Baseline الموحد. استخدم طبقة التخصيص بدل تعديل مخططها الفيزيائي من هنا.',
      'physical_table': 'الجدول الفعلي',
      'new_field': 'حقل جديد',
      'edit_field': 'تعديل الحقل',
      'delete_field': 'حذف الحقل',
      'delete_field_confirm': 'هل تريد حذف هذا الحقل وعموده الفعلي وبياناته؟',
      'field_name': 'اسم الحقل',
      'field_type': 'نوع الحقل',
      'render_as': 'العرض كـ',
      'render_as_help': 'اختر عنصر الواجهة دون تغيير نوع تخزين الحقل. AUTO يستخدم الميتاداتا والاستنتاج الآمن.',
      'invalid_field_name': 'يجب أن يبدأ اسم الحقل بحرف أو شرطة سفلية ويحتوي فقط على حروف وأرقام وشرطة سفلية.',
      'field_type_storage_guard': 'يُمنع التحويل إلى نوع تخزين SQL مختلف لحماية البيانات الموجودة.',
      'default_value': 'القيمة الافتراضية',
      'description': 'الوصف',
      'in_list_view': 'إظهار في القائمة',
      'standard_filter': 'فلتر قياسي',
      'searchable': 'قابل للبحث',
      'allow_on_submit': 'السماح بعد الاعتماد',
      'depends_on': 'شرط الإظهار',
      'mandatory_depends_on': 'شرط الإلزام',
      'read_only_depends_on': 'شرط القراءة فقط',
      'fetch_from': 'جلب من',
      'precision': 'الدقة العشرية',
      'length': 'الطول',
      'move_up': 'تحريك لأعلى',
      'move_down': 'تحريك لأسفل',
      'link_options_help': 'أدخل اسم نوع المستند الهدف.',
      'dynamic_link_options_help': 'أدخل اسم الحقل الذي يحتوي نوع المستند الهدف.',
      'table_options_help': 'أدخل اسم Child DocType.',
      'select_options_help': 'أدخل خيارًا واحدًا في كل سطر.',
      'submitted': 'تم الاعتماد',
      'cancelled': 'تم الإلغاء',
      'cancel_document': 'إلغاء المستند',
      'cancel_document_confirm': 'هل تريد إلغاء هذا المستند المعتمد؟',
      'search_desk': 'بحث في مساحات العمل وأنواع المستندات',
      'workspace_navigation': 'تنقل مساحة العمل',
      'workspace_shortcuts': 'الاختصارات',
      'workspace_links': 'الروابط',
      'workspace_not_found': 'مساحة العمل غير موجودة',
      'page_not_found': 'الصفحة غير موجودة',
      'page_metadata_ready': 'الصفحة جاهزة لإضافة محتوى ميتاداتا.',
      'page_controller_missing': 'متحكم الصفحة غير مثبت في بيئة التشغيل الحالية.',
      'page_target_unavailable': 'هدف الصفحة غير متاح أو غير مسموح الوصول إليه.',
      'workspace_charts': 'رسوم لوحة المعلومات',
      'workspace_quick_lists': 'القوائم السريعة',
      'workspace_quick_list': 'قائمة سريعة',
      'workspace_chart_requires_port': 'هذا الرسم يحتاج تحويل مصدر التقرير/البيانات أو لا توجد له بيانات محلية بعد.',
      'number_card': 'بطاقة رقمية',
      'unknown_doctype': 'نوع المستند غير معروف',
      'invalid_link': 'الرابط لا يشير إلى سجل موجود',
      'report_requires_porting': 'هذا التقرير المستورد ما زال يحتاج إلى تحويل',
      'report_available_in_reports': 'هذا التقرير متاح في قسم التقارير',
      'erpnext_v16_stack': 'حزمة ERPNext v16 + Frappe v16',
      'erpnext_stack_help': 'الخيار الموصى به للتحويل. يقوم WMN بتنزيل وتحويل Frappe v16 أولاً ثم ERPNext v16 حتى تكون أنواع المستندات والاعتماديات المشتركة متاحة قبل استيراد ميتاداتا ERPNext.',
      'download_erpnext_stack': 'تنزيل وتحويل حزمة ERPNext v16',
      'select_local_erpnext_stack': 'اختيار ملفات Frappe + ERPNext ZIP المحلية',
      'local_stack_conversion_start': 'بدء تحويل حزمة Frappe/ERPNext المحلية…',
      'local_stack_conversion_complete': 'اكتمل تحويل حزمة Frappe/ERPNext المحلية.',
      'erpnext_stack_start': 'بدء تحويل حزمة ERPNext v16…',
      'frappe_core_downloading': 'جارٍ تنزيل وتحويل نواة Frappe v16…',
      'erpnext_downloading': 'جارٍ تنزيل وتحويل ERPNext v16…',
      'erpnext_stack_complete': 'اكتمل تحويل حزمة ERPNext v16. راجع مهام التحويل لملفات Python وControllers وHooks التي تحتاج تنفيذًا أصليًا داخل WMN.',
      'frappe_package_help': 'تحويل حزمة تطبيق Frappe / ERPNext كاملة إلى ميتاداتا WMN ومساحات عمل وأنواع مستندات ومهام تحويل موثقة.',
      'app_name_override': 'اسم التطبيق البديل',
      'optional': 'اختياري',
      'convert_zip_app': 'تحويل حزمة التطبيق ZIP',
      'convert_zip_help': 'اختر ملف ZIP لتطبيق Frappe/ERPNext. يقوم WMN بتحليل الميتاداتا دون تشغيل Python.',
      'select_app_zip': 'اختيار ملف التطبيق ZIP',
      'github_app_download': 'تنزيل من GitHub',
      'github_repository': 'مستودع GitHub',
      'git_ref': 'الفرع / المرجع',
      'download_and_convert': 'تنزيل وتحويل',
      'downloading_app': 'جارٍ تنزيل حزمة التطبيق…',
      'converting_app': 'جارٍ تحويل حزمة التطبيق…',
      'advanced_single_doctype_import': 'متقدم: استيراد DocType JSON منفرد',
      'converted_doctypes': 'أنواع المستندات المحولة',
      'converted_workspaces': 'مساحات العمل المحولة',
      'converted_pages': 'الصفحات المحولة',
      'placeholder_dependencies': 'اعتماديات مؤقتة',
      'porting_tasks': 'مهام التحويل',
      'artifacts': 'مكونات التطبيق',
      'converted': 'تم التحويل',
      'needs_port': 'يحتاج تحويل',
      'failed': 'فشل',
      'conversion_artifacts': 'مكونات التحويل',
      'showing_first_500': 'يتم عرض أول 500 سجل',
      'frappe_package_limitations': 'لا يقوم WMN مطلقًا بتشغيل Python الخاص بـFrappe أو SQL حر. يتم حفظ Controllers وHooks والتقارير وWorkflows وServer Scripts غير المدعومة كمهام تحويل مع مسارات ملفاتها الأصلية.',
      'framework_foundation': 'نواة إطار العمل',
      'data_import_export': 'استيراد / تصدير البيانات',
      'data_import': 'استيراد البيانات',
      'data_export': 'تصدير البيانات',
      'doctype': 'نوع المستند',
      'import_mode': 'وضع الاستيراد',
      'insert_new': 'إدراج سجلات جديدة',
      'update_existing': 'تحديث السجلات الموجودة',
      'upsert': 'إدراج أو تحديث',
      'copy_template': 'نسخ قالب CSV',
      'download_template': 'تنزيل القالب',
      'select_file': 'اختيار ملف',
      'fields': 'الحقول',
      'import_records': 'استيراد السجلات',
      'rows_success': 'الصفوف الناجحة',
      'rows_failed': 'الصفوف الفاشلة',
      'file_format': 'صيغة الملف',
      'export_records': 'تصدير السجلات',
      'selected_fields': 'الحقول المحددة',
      'save_file': 'حفظ الملف',
      'template_copied': 'تم نسخ القالب',
      'frappe_app_import': 'محول تطبيقات Frappe الخارجية',
      'source_porting_workbench': 'منضدة تحويل المصدر',
      'search_source_files': 'البحث في ملفات المصدر',
      'source_units': 'وحدات المصدر',
      'no_source_units': 'لا توجد وحدات مصدر',
      'no_auto_conversion': 'لم يتم إنشاء تحويل تلقائي آمن لهذه الوحدة البرمجية.',
      'conversion_status': 'حالة التحويل',
      'conversion_strategy': 'استراتيجية التحويل',
      'confidence': 'درجة الثقة',
      'diagnostics': 'التشخيص',
      'dependencies': 'الاعتماديات',
      'open_source_porting_workbench': 'فتح منضدة تحويل المصدر',
      'imported_apps': 'التطبيقات المستوردة',
      'frappe_import_help': 'استيراد Metadata الخاصة بـ Frappe DocType وتحويلها إلى DocTypes أصلية داخل WMN.',
      'source_app': 'التطبيق المصدر',
      'import_doctype_json': 'استيراد DocType JSON',
      'frappe_import_limitations': 'يتم تحويل Metadata تلقائيًا. أما Python Controllers و hooks.py وSQL الحر والمهام الخلفية فتحتاج نقلًا صريحًا إلى محركات أو Scripts في WMN.',
      'search_doctype': 'بحث في أنواع المستندات',
      'dynamic_doctype': 'نوع مستند ديناميكي قديم',
      'physical_doctype': 'نوع مستند بجدول فعلي',
      'script_reports': 'تقارير السكربت',
      'new_script_report': 'تقرير سكربت جديد',
      'script_report': 'تقرير سكربت',
      'reference_doctype': 'نوع المستند المرجعي',
      'runtime_filters_json': 'فلاتر التشغيل JSON',
      'columns_json': 'الأعمدة JSON',
      'report_filters': 'فلاتر التقرير',
      'report_results': 'نتائج التقرير',
      'invalid_number': 'رقم غير صالح',
      'invalid_json': 'JSON غير صالح',
      'new_record': 'سجل جديد',
      'quick_create': 'إضافة سريعة',
      'manage_records': 'إدارة السجلات',
      'submittable': 'قابل للاعتماد',
      'filter': 'فلتر',
      'clear_filters': 'مسح الفلاتر',
      'id': 'المعرف',
      'open': 'فتح',
      'delete_record_confirm': 'هل تريد حذف هذا السجل؟',
      'field': 'الحقل',
      'rate': 'السعر',
      'erp_home': 'الرئيسية',
      'buying': 'المشتريات',
      'debit_account': 'الحساب المدين',
      'credit_account': 'الحساب الدائن',
      'create_next': 'إنشاء المستند التالي',
      'submit_document': 'اعتماد المستند',
      'required_by': 'مطلوب بتاريخ',
      'source_document': 'المستند المصدر',
      'receive_payment': 'استلام دفعة',
      'internal_transfer': 'تحويل داخلي',
      'new_payment_entry': 'سند دفع جديد',
      'allocation': 'التخصيص',
      'unallocated': 'غير مخصص',
      'erpnext_reference': 'المرجع الوظيفي ERPNext',
      'functional_parity': 'محاكاة السلوك الوظيفي',
      'procurement_flow': 'دورة المشتريات',
      'selling_flow': 'دورة المبيعات',
      'inventory_flow': 'دورة المخزون',
      'module_status': 'حالة الموديول',
      'operational': 'تشغيلي',
      'foundation': 'أساس جاهز للتوسعة',

      'receipt': 'الإيصال',
      'grand_total': 'الإجمالي النهائي',
      'payments': 'المدفوعات',
      'print_job': 'مهمة الطباعة',
      'selling_rate': 'سعر البيع',
      'allow_negative_stock': 'السماح بالمخزون السالب',
      'tracked_by_batch': 'تتبع بالدفعة',
      'tracked_by_serial': 'تتبع بالسيريال',
      'barcode': 'الباركود',
      'add_barcode': 'إضافة باركود',
      'unknown_barcode': 'لم يتم التعرف على الباركود',
      'scan_barcode': 'مسح / إدخال باركود',
      'manual_discount_total': 'الخصم اليدوي',
      'paid_amount': 'المبلغ المدفوع',
      'add_row': 'إضافة سطر',
      'remove': 'حذف',
      'open_cash_session_first': 'افتح جلسة صندوق أولاً',
      'session_open': 'جلسة الصندوق مفتوحة',
      'no_open_session': 'لا توجد جلسة صندوق مفتوحة',
      'new_pin_optional': 'رمز PIN جديد (اختياري)',
      'display_name': 'الاسم الظاهر',
      'connection_type': 'نوع الاتصال',
      'network': 'شبكة',
      'serial': 'تسلسلي',
      'windows_raw': 'Windows Raw',
      'qz': 'QZ Tray',
      'usb': 'USB',
      'bluetooth': 'بلوتوث',
      'system_print': 'طباعة النظام / PDF',
      'save_settings': 'حفظ الإعدادات',
      'provider': 'المزود',
      'configuration_json': 'إعدادات JSON',
      'generic_rest': 'REST عام',
      'returned_qty': 'الكمية المرتجعة',
      'available_to_return': 'المتاح للإرجاع',
      'condition_json': 'شروط JSON',
      'action_json': 'إجراءات JSON',
      'enabled': 'مفعل',
      'details': 'التفاصيل',
      'status': 'الحالة',
      'date': 'التاريخ',
      'count': 'العدد',
      'app_name': 'نظام WMN المستقل',
      'items': 'الأصناف',
      'rules': 'القواعد التجارية',
      'reports': 'التقارير',
      'system': 'النظام',
      'customization': 'التخصيص',
      'custom_fields': 'الحقول المخصصة',
      'property_overrides': 'تجاوز خصائص الحقول',
      'client_scripts': 'سكربتات العميل',
      'server_scripts': 'سكربتات الخادم',
      'script_logs': 'سجل تنفيذ السكربتات',
      'add_custom_field': 'إضافة حقل مخصص',
      'add_property_override': 'إضافة تجاوز خاصية',
      'add_client_script': 'إضافة سكربت عميل',
      'add_server_script': 'إضافة سكربت خادم',
      'label': 'التسمية',
      'insert_after': 'إدراج بعد',
      'options': 'الخيارات',
      'required': 'إلزامي',
      'read_only': 'للقراءة فقط',
      'hidden': 'مخفي',
      'script': 'السكربت',
      'event': 'الحدث',
      'property': 'الخاصية',
      'run_test': 'اختبار التشغيل',
      'script_success': 'تم تنفيذ السكربت بنجاح',
      'customization_help': 'وسّع WMN بدون تعديل نواة نظام ERP.',
      'tax_id': 'الرقم الضريبي',
      'parent_group': 'المجموعة الأب',
      'set_active': 'تعيين كنشط',
      'users': 'المستخدمون',
      'add': 'إضافة',
      'create': 'إنشاء',
      'edit': 'تعديل',
      'delete': 'حذف',
      'disabled': 'معطل',
      'search': 'بحث',
      'no_records': 'لا توجد سجلات',
      'mobile': 'الجوال',
      'email': 'البريد الإلكتروني',
      'add_user': 'إضافة مستخدم',
      'edit_user': 'تعديل المستخدم',
      'username': 'اسم المستخدم',
      'role': 'الدور',
      'confirm_delete': 'تأكيد الحذف',
      'delete_or_disable_help': 'إذا كان السجل مستخدمًا في حركات فعلية فسيتم تعطيله بدل حذف السجل التاريخي.',
      'record_deleted': 'تم حذف السجل.',
      'record_disabled_used': 'السجل مستخدم وتم تعطيله بدل حذفه.',
      'cannot_delete': 'لا يمكن الحذف',
      'edit_rule': 'تعديل القاعدة',
      'all': 'الكل',
      'unpaid': 'غير مدفوعة',
      'partly_paid': 'مدفوعة جزئيًا',
      'document_type': 'نوع المستند',
      'all_groups': 'الكل',
      'stock': 'المخزون',
      'cart': 'السلة',
      'clear': 'مسح',
      'manual_discount': 'خصم يدوي',
      'payment': 'الدفع',
      'gross_total': 'الإجمالي قبل الخصم',
      'discounts': 'الخصومات',
      'discount': 'الخصم',
      'total': 'الإجمالي',
      'quantity': 'الكمية',
      'batch': 'الدفعة',
      'serial_numbers': 'الأرقام التسلسلية',
      'scan_or_enter_serials': 'امسح أو أدخل الأرقام التسلسلية كل رقم في سطر',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      'code': 'الرمز',
      'name': 'الاسم',
      'value': 'القيمة',
      'reason': 'السبب',
      'percentage': 'نسبة',
      'amount': 'مبلغ',
      'approve': 'اعتماد',
      'print': 'طباعة',
      'return': 'مرتجع',
      'paid': 'المدفوع',
      'outstanding': 'المتبقي',
      'lifecycle': 'حالة المستند',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'الإنجليزية',
      'appearance': 'المظهر',
      'theme_system': 'حسب النظام',
      'theme_light': 'فاتح',
      'theme_dark': 'داكن',
      'printing': 'الطباعة',
      'print_settings': 'إعدادات الطباعة',
      'preview_only': 'معاينة فقط',
      'windows_printer_share': 'مشاركة طابعة Windows الخام',
      'host': 'المضيف',
      'port': 'المنفذ',
      'com_port': 'منفذ COM',
      'printer_path': 'مسار الطابعة',
      'cut_paper': 'قص الورق',
      'open_cash_drawer': 'فتح درج النقد',
      'auto_print': 'طباعة تلقائية بعد البيع',
      'paper_width': 'عرض الورق',
      'print_job_sent': 'تم إرسال مهمة الطباعة.',
      'export_pdf': 'تصدير / مشاركة PDF',
      'system_print_mode': 'تخطيط الطباعة النظامية',
      'receipt_layout': 'تخطيط الإيصال',
      'a4_layout': 'تخطيط A4',
      'barcode_structure': 'هيكل الباركود',
      'add_barcode_structure': 'إضافة هيكل باركود',
      'edit_barcode_structure': 'تعديل هيكل الباركود',
      'prefix': 'البادئة',
      'quantity_start': 'بداية الكمية',
      'quantity_length': 'طول الكمية',
      'quantity_divisor': 'مقسوم الكمية',
      'price_start': 'بداية السعر',
      'price_length': 'طول السعر',
      'price_divisor': 'مقسوم السعر',
      'add_gateway': 'إضافة بوابة',
      'edit_gateway': 'تعديل بوابة الدفع',
      'test_gateway': 'بوابة اختبار',
      'generic_rest_lan': 'REST عام / شبكة محلية',
      'geidea_rest': 'REST متوافق مع جيديا',
      'endpoint_url': 'رابط الخدمة',
      'electronic_gateway': 'بوابة دفع إلكترونية',
      'gateway_profile': 'ملف بوابة الدفع',
      'cash': 'نقد',
      'card': 'بطاقة',
      'bank': 'بنك',
      'reference_no': 'رقم المرجع',
      'add_payment': 'إضافة دفعة',
      'credit_sale': 'بيع آجل',
      'credit_not_allowed': 'البيع بالآجل والدفع الجزئي معطلان في ملف نقطة البيع النشط.',
      'remaining': 'المتبقي',
      'add_rule': 'إضافة قاعدة',
      'priority': 'الأولوية',
      'rule_type': 'نوع القاعدة',
      'apply_on': 'التطبيق على',
      'brand': 'العلامة التجارية',
      'discount_percentage': 'نسبة الخصم',
      'discount_amount': 'مبلغ الخصم',
      'fixed_rate': 'سعر ثابت',
      'min_qty': 'الحد الأدنى للكمية',
      'min_amount': 'الحد الأدنى للمبلغ',
      'buy_x_get_y': 'اشترِ X واحصل على Y / صنف مجاني',
      'free_qty': 'الكمية المجانية',
      'supervisor': 'المشرف',
      'pin': 'الرمز السري',
      'edit_profile': 'تعديل الملف',
      'company': 'الشركة',
      'branch': 'الفرع',
      'currency': 'العملة',
      'allow_credit': 'السماح بالبيع الآجل',
      'yes': 'نعم',
      'no': 'لا',
      'cash_session': 'جلسة الصندوق',
      'open_session': 'فتح جلسة',
      'close_session': 'إغلاق الجلسة',
      'opening_cash': 'النقد الافتتاحي',
      'actual_cash': 'النقد الفعلي',
      'expected': 'المتوقع',
      'difference': 'الفرق',
      'cash_movement': 'حركة الصندوق',
      'cash_in': 'إدخال نقدي',
      'cash_out': 'إخراج نقدي',
      'note': 'ملاحظة',
      'ui_preferences': 'تفضيلات واجهة نقطة البيع',
      'grid_view': 'عرض شبكي',
      'button_view': 'عرض أزرار',
      'show_cart_counter': 'إظهار عدد الصنف في السلة',
      'auto_open_receipt': 'فتح الإيصال بعد البيع',
      'database': 'قاعدة البيانات',
      'schema_version': 'إصدار المخطط',
      'storage': 'التخزين',
      'location': 'الموقع',
      'payment_method_summary': 'ملخص طرق الدفع',
      'cash_movement_report': 'حركات الصندوق',
      'shift_closing_report': 'إغلاق الوردية',
      'report_builder': 'منشئ التقارير',
      'saved_reports': 'التقارير المحفوظة',
      'new_report': 'تقرير جديد',
      'edit_report': 'تعديل التقرير',
      'run_report': 'تشغيل التقرير',
      'show_report': 'عرض التقرير',
      'print_preview': 'طباعة / معاينة',
      'print_format': 'تنسيق الطباعة',
      'letter_head': 'الترويسة',
      'default_letter_head': 'الافتراضية / تلقائي',
      'no_letter_head': 'بدون ترويسة',
      'print_language': 'لغة الطباعة',
      'refresh_preview': 'تحديث المعاينة',
      'print_template_help': 'رموز قالب الطباعة WMN',
      'report_creation_guide': 'دليل إنشاء التقرير',
      'report_creation_intro': 'اختر نوع التقرير ثم عرّف الفلاتر والأعمدة داخل جداول Child Tables القابلة للتعديل أدناه. كود Query وManaged Script يُحفظ في Storage، ويمكن مزامنة تعريف التقرير القياسي كاملًا من مجلد التقرير داخل التطبيق.',
      'report_builder_creation_help': 'Report Builder: اختر Reference DocType/مصدر البيانات ثم أضف الفلاتر والأعمدة كسجلات داخل الجداول. لا يحتاج SQL.',
      'query_report_creation_help': 'Query Report: أضف الفلاتر والأعمدة كسجلات جدول ثم عدّل استعلام SELECT/WITH واحدًا للقراءة داخل محرر SQL. استخدم %(filter_name)s وسيقوم WMN بربط القيم وحفظ SQL في Storage.',
      'script_report_creation_help': 'Script Report: أضف الفلاتر والأعمدة كسجلات جدول ثم استخدم NATIVE_HANDLER مسجلًا أو Managed STORAGE_FILE قابلًا للتحرير. المثال المدمج يعرض JOIN حقيقيًا بين جدولين.',
      'query_sql_code': 'كود Query SQL',
      'query_sql_code_help': 'يظهر كود SQL هنا للتعلم والتعديل، لكن WMN يحفظه فعليًا في Storage ويحتفظ داخل Report بمسار المصدر فقط.',
      'query_sql_required': 'كود Query SQL مطلوب.',
      'script_source_code': 'كود Script Report',
      'native_handler_source_help': 'الـNative Handler هو كود Dart مترجم. الأمثلة المدمجة تعرض نسخة قراءة فقط من الكود الحقيقي حتى يفهم المستخدم منطق التقرير.',
      'managed_script_source_help': 'كود Managed Script يُحفظ خارج قاعدة البيانات داخل WMN Storage.',
      'native_handler_source_preview': 'معاينة كود Native Handler',
      'managed_script_source': 'كود Managed Script',
      'native_handler_key': 'مفتاح Native Handler',
      'source_path': 'مسار المصدر',
      'script_source_required': 'كود Script مطلوب.',
      'script_storage_unavailable': 'Storage الخاص بالسكريبت غير متاح.',
      'report_example_guide': 'تقرير Example عملي',
      'select_doctype_first': 'اختر نوع المستند المستهدف أولًا',
      'how_to_create': 'طريقة الإنشاء',
      'report_name_required': 'اسم التقرير مطلوب.',
      'report_reference_doctype_required': 'يجب تحديد Reference DocType لتقرير Report Builder.',
      'report_columns_required': 'أضف عمودًا واحدًا على الأقل للتقرير.',
      'delete_report': 'حذف التقرير',
      'report_name': 'اسم التقرير',
      'data_source': 'مصدر البيانات',
      'report_columns': 'أعمدة التقرير',
      'filters': 'الفلاتر',
      'add_filter': 'إضافة فلتر',
      'operator': 'المعامل',
      'aggregation': 'التجميع',
      'sort_by': 'الترتيب حسب',
      'sort_direction': 'اتجاه الترتيب',
      'ascending': 'تصاعدي',
      'descending': 'تنازلي',
      'row_limit': 'الحد الأقصى للصفوف',
      'copy_csv': 'نسخ CSV',
      'csv_copied': 'تم نسخ CSV إلى الحافظة.',
      'report_saved': 'تم حفظ التقرير.',
      'report_deleted': 'تم حذف التقرير.',
      'select_columns': 'اختر عمودًا واحدًا على الأقل.',
      'no_saved_reports': 'لا توجد تقارير مخصصة حتى الآن.',
      'report_builder_help': 'أنشئ تقارير بدون SQL عبر اختيار الحقول والفلاتر والتجميعات.',
      'report_rows': 'الصفوف',
      'report_duration': 'مدة التنفيذ',
      'milliseconds': 'مللي ثانية',
      'none': 'بدون',
      'equals': 'يساوي',
      'not_equals': 'لا يساوي',
      'greater_than': 'أكبر من',
      'greater_or_equal': 'أكبر من أو يساوي',
      'less_than': 'أقل من',
      'less_or_equal': 'أقل من أو يساوي',
      'contains': 'يحتوي',
      'starts_with': 'يبدأ بـ',
      'is_empty': 'فارغ',
      'is_not_empty': 'غير فارغ',
      'camera_scan': 'المسح بالكاميرا',
      'camera_scan_hint': 'وجّه الكاميرا نحو الباركود أو رمز QR',
      'camera_error': 'خطأ في الكاميرا',
      'barcode_added': 'تمت إضافة الباركود',
      'scanning': 'جارٍ المسح...',
      'capture_scan': 'التقاط ومسح',
      'printer_name': 'اسم / مسار الطابعة',
      'qz_printer_name': 'اسم طابعة QZ',
      'usb_device_name': 'اسم جهاز USB',
      'usb_vendor_id': 'معرّف الشركة USB Vendor ID',
      'usb_product_id': 'معرّف المنتج USB Product ID',
      'bluetooth_name': 'اسم جهاز البلوتوث',
      'bluetooth_address': 'عنوان البلوتوث',
      'preview': 'معاينة',
      'serial_com': 'ESC/POS تسلسلي / COM',
      'windows_raw_label': 'Windows Raw',
      'usb_adapter': 'محول USB',
      'bluetooth_adapter': 'محول بلوتوث',
      'no_rules_yet': 'لا توجد قواعد حتى الآن.',
      'if_label': 'إذا',
      'do_label': 'فنفّذ',
      'uses': 'الاستخدامات',
      'conditions': 'الشروط',
      'actions': 'الإجراءات',
      'max_uses_optional': 'الحد الأقصى للاستخدامات (اختياري)',
      'advanced_rule_help': 'خيارات القواعد المتقدمة: الصنف/المجموعة/العلامة/الوحدة، حدود الكمية والمبلغ، السعر الثابت، خصم نسبة/مبلغ، تعدد القواعد، الخصم على السعر المخفض، قواعد المعاملة، الربط بالكوبون، التراكم، خصم المنتج والأصناف المجانية.',
      'no_data': 'لا توجد بيانات',
      'available': 'المتاح',
      'prefix_label': 'البادئة',
      'item_segment': 'مقطع الصنف',
      'test_provider': 'اختبار',
      'generic_rest_provider': 'REST عام / شبكة محلية',
      'geidea_compatibility': 'توافق جيديا',
      'stc_compatibility': 'توافق STC SoftPOS',
      'more': 'المزيد',
      'view_cart': 'عرض السلة',
      'cart_empty': 'السلة فارغة',
      'rule_scope': 'تنطبق على',
      'target': 'الهدف',
      'benefit': 'الميزة / الخصم',
      'validity': 'فترة الصلاحية',
      'advanced_options_preserved': 'تم الاحتفاظ بالخيارات المتقدمة الموجودة في هذه القاعدة داخليًا دون عرض JSON للمستخدم.',
      'basic_information': 'البيانات الأساسية',
      'whole_transaction': 'الفاتورة كاملة',
      'benefit_type': 'نوع الميزة',
      'max_qty': 'الحد الأقصى للكمية',
      'max_amount': 'الحد الأقصى للمبلغ',
      'cumulative_rule': 'قاعدة تراكمية',
      'cumulative_rule_help': 'احتساب مشتريات العميل السابقة المؤهلة عند تقييم هذه القاعدة.',
      'buy_qty': 'كمية الشراء',
      'max_discount_optional': 'الحد الأقصى للخصم (اختياري)',
      'stackable': 'يمكن جمعها مع قواعد أخرى',
      'stackable_help': 'السماح بتطبيق قاعدة تسعير أو عرض مؤهل آخر في نفس العملية.',
      'valid_from': 'صالحة من',
      'valid_upto': 'صالحة حتى',
      'name_required': 'الاسم أو الكود مطلوب.',
      'max_uses': 'الحد الأقصى للاستخدام',
      'refresh': 'تحديث',
    },
  };

  String t(String key) => _values[languageCode]?[key] ?? _values['en']?[key] ?? key;
}

class WmnL10nScope extends InheritedNotifier<WmnLocaleController> {
  const WmnL10nScope({
    super.key,
    required WmnLocaleController controller,
    required super.child,
  }) : super(notifier: controller);

  static WmnLocaleController controllerOf(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<WmnL10nScope>();
    if (scope == null) throw StateError('WMN localization scope is not available.');
    return scope.notifier!;
  }

  static WmnStrings of(BuildContext context) {
    final controller = controllerOf(context);
    return WmnStrings(controller.languageCode);
  }
}


extension WmnLocalizationContext on BuildContext {
  String wmnT(String key) => WmnL10nScope.of(this).t(key);
}
